title: Architectural Inputs Management
description: A Meteor Application to specify Architectural Inputs and Decisions. These include quality scenarios, architectural constraints, decisions, views and models.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
