title: meteor-application-template
description: A template for quickly starting Meteor application development
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
